version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: ./manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app/pixel
    ports:
      - "8000:8000"
    depends_on:
      - db
