version: '2.1'

services:
  db:
    image: postgres:9.6
    env_file: env.d/test
  web:
    build:
      context: .
      args:
        IS_NOT_PRODUCTION: "true"
    env_file: env.d/test
    volumes:
      - .git:/app/pixel/.git
    depends_on:
      - db
