version: '2.1'

services:
  db:
    image: postgres
    env_file: env.d/test
  web:
    build:
      context: .
      args:
        DEVELOPMENT: "true"
    env_file: env.d/test
    depends_on:
      - db
