version: '2.1'

# TODO
# 1. handle TAG substitution
# 2. handle HOST_PORT substitution
# 3. create .env file
# 4. copy ./docker/etc/nginx/conf.d/pixel.conf on host

services:
  db:
    image: postgres:9.6
    env_file: .env
  web:
    image: candihub/pixel:TAG
    env_file: .env
    volumes:
      - media:/app/pixel/public/media
      - static:/app/pixel/public/static
      - run:/app/pixel/run
    depends_on:
      - db
  proxy:
    image: nginx
    volumes:
      - ./docker/etc/nginx/conf.d/pixel.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - web
    ports:
      - "HOST_PORT:80"
    depends_on:
      - web

volumes:
  media:
  run:
  static:
