version: 2
jobs:

  build_frontend:
    working_directory: ~/pixel
    docker:
      - image: circleci/node:8
        environment:
          CI_BUILD_FRONTEND: 1
    steps:
      - checkout
      - restore_cache:
          keys:
          - frontend-deps-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies & build styles
          command: |
            make bootstrap
      - save_cache:
          paths:
            - ~/pixel/static
            - ~/pixel/node_modules
          key: frontend-deps-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}

  build_backend:
    machine: true
    steps:
      - checkout
      - restore_cache:
          keys:
          - frontend-deps-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Login to DockerHub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Build container
          command: |
            docker build -t candihub/pixel:$CIRCLE_BRANCH .
      - run:
          name: Publish container
          command: |
            docker push candihub/pixel:$CIRCLE_BRANCH

  build_dev_backend:
    working_directory: /app/pixel
    docker:
      - image: candihub/pixel:$CIRCLE_BRANCH
    steps:
      - restore_cache:
          keys:
            - backend-dev-deps-v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          name: Install development dependencies
          command: |
            make install-ci
      - save_cache:
          paths:
            - ~/.local/share/virtualenvs
          key: backend-dev-deps-v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

  lint_backend:
    working_directory: /app/pixel
    docker:
      - image: candihub/pixel:$CIRCLE_BRANCH
    steps:
      - restore_cache:
          keys:
            - backend-dev-deps-v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          name: Lint the code
          command: |
            make lint-ci

  test_backend:
    working_directory: /app/pixel
    docker:
      - image: candihub/pixel:$CIRCLE_BRANCH
        environment:
          DJANGO_SETTINGS_MODULE: pixel.settings
          DJANGO_CONFIGURATION: Test
          DJANGO_SECRET_KEY: ThisIsAnExampleKeyForDevPurposeOnly
          POSTGRES_HOST: localhost
          POSTGRES_DB: pixel
          POSTGRES_USER: pixel
          POSTGRES_PASSWORD: pixel42
      - image: postgres:9.6
        environment:
          POSTGRES_DB: pixel
          POSTGRES_USER: pixel
          POSTGRES_PASSWORD: pixel42
    steps:
      - restore_cache:
          keys:
            - backend-dev-deps-v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          name: Test the code
          command: |
            sleep 10
            make test-ci
      - run:
          name: Create git repository
          command: |
            git init
            git remote add origin $CIRCLE_REPOSITORY_URL
            mkdir ~/.ssh
            ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
            git fetch
            git reset origin/$CIRCLE_BRANCH
            git checkout origin/$CIRCLE_BRANCH
      - run:
          name: Report code coverage
          command: |
            make coverage-ci
          when: on_success

workflows:
  version: 2

  pixel:
    jobs:
      - build_frontend
      - build_backend:
          requires:
            - build_frontend
      - build_dev_backend:
          requires:
            - build_backend
      - lint_backend:
          requires:
            - build_dev_backend
      - test_backend:
          requires:
            - build_dev_backend
