version: 2
jobs:

  build:
    working_directory: ~/pixel
    docker:
      - image: circleci/python:3.6.1
        environment:
          PIPENV_VENV_IN_PROJECT: 1
    steps:
      - checkout
      - restore_cache:
          keys:
          - backend-deps-v2-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      # In user mode, Pipenv is installed to $HOME/.local/bin
      - run:
          name: Add Pipenv to the PATH
          command: |
            echo "export PATH=~/.local/bin:$PATH" >> $BASH_ENV
      - run:
          name: Install dependencies
          command: |
            pip3 install --user pipenv
            pipenv install --dev
      - save_cache:
          paths:
            - ~/.local
            - ~/pixel/.venv
          key: backend-deps-v2-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

  lint:
    working_directory: ~/pixel
    docker:
      - image: circleci/python:3.6.1
        environment:
          PIPENV_VENV_IN_PROJECT: 1
    steps:
      - checkout
      - restore_cache:
          keys:
          - backend-deps-v2-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          name: Add Pipenv & installed tools to the PATH
          command: |
            echo "export PATH=~/.local/bin:~/pixel/.venv/bin:$PATH" >> $BASH_ENV
      - run:
          name: Lint the code
          command: pipenv run flake8

  test:
    working_directory: ~/pixel
    docker:
      - image: circleci/python:3.6.1
        environment:
          PIPENV_VENV_IN_PROJECT: 1
    steps:
      - checkout
      - restore_cache:
          keys:
          - backend-deps-v2-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          name: Add Pipenv & installed tools to the PATH
          command: |
            echo "export PATH=~/.local/bin:~/pixel/.venv/bin:$PATH" >> $BASH_ENV
      - run:
          name: Test the code
          command: |
            pipenv run pytest

  coverage:
    working_directory: ~/pixel
    docker:
      - image: circleci/python:3.6.1
        environment:
          PIPENV_VENV_IN_PROJECT: 1
    steps:
      - checkout
      - restore_cache:
          keys:
          - backend-deps-v2-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          name: Add Pipenv & installed tools to the PATH
          command: |
            echo "export PATH=~/.local/bin:~/pixel/.venv/bin:$PATH" >> $BASH_ENV
      - run:
          name: Report code coverage
          command: |
            pipenv run coveralls

workflows:
  version: 2

  backend:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
      - coverage:
          requires:
            - test
