# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
        ('core', '0002_auto_20171012_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='species', related_query_name='species', to='data.Repository'),
        ),
    ]
