# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_species_repository'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='species', related_query_name='species', to='data.Entry'),
        ),
    ]
