# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_experiment_data_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='notebook_url',
            field=models.URLField(blank=True, help_text='Paste an URL to your Jupiter Notebook here', verbose_name='Notebook url'),
        ),
    ]
