# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 12:57
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_strain_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='omics_area',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments', related_query_name='experiment', to='core.OmicsArea'),
        ),
    ]
