# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 13:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20171017_1257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pixeler',
            options={'verbose_name': 'Pixeler', 'verbose_name_plural': 'Pixelers'},
        ),
    ]
