# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 20:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
        ('core', '0006_remove_experiment_primary_data_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiment',
            name='data_sources',
        ),
        migrations.RemoveField(
            model_name='omicsunit',
            name='custom_identifier',
        ),
        migrations.RemoveField(
            model_name='omicsunit',
            name='reference_database',
        ),
        migrations.RemoveField(
            model_name='omicsunit',
            name='reference_identifier',
        ),
        migrations.RemoveField(
            model_name='species',
            name='reference_database',
        ),
        migrations.RemoveField(
            model_name='species',
            name='reference_identifier',
        ),
        migrations.AddField(
            model_name='experiment',
            name='entries',
            field=models.ManyToManyField(related_name='experiments', related_query_name='experiment', to='data.Entry'),
        ),
        migrations.AddField(
            model_name='omicsunit',
            name='reference',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='data.Entry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='species',
            name='reference',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='species', related_query_name='species', to='data.Entry'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analysis',
            name='pixeler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', related_query_name='analysis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='omics_domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments', related_query_name='experiment', to='core.OmicsDomain'),
        ),
        migrations.AlterField(
            model_name='omicsunit',
            name='strain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='omics_units', related_query_name='omics_unit', to='core.Strain'),
        ),
        migrations.AlterField(
            model_name='omicsunit',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='omics_units', related_query_name='omics_unit', to='core.OmicsUnitType'),
        ),
        migrations.AlterField(
            model_name='pixel',
            name='omics_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pixels', related_query_name='pixel', to='core.OmicsUnit'),
        ),
        migrations.AlterField(
            model_name='strain',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strains', related_query_name='strain', to='core.Species'),
        ),
        migrations.DeleteModel(
            name='DataSource',
        ),
        migrations.DeleteModel(
            name='PublicDatabase',
        ),
    ]
