# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 14:22
from __future__ import unicode_literals

import apps.core.mixins
import apps.core.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20171106_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='PixelSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pixels_file', models.FileField(upload_to=apps.core.models.PixelSet.pixelset_upload_to, verbose_name='Pixels file')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pixelsets', related_query_name='pixelset', to='core.Analysis')),
            ],
            bases=(apps.core.mixins.UUIDModelMixin, models.Model),
        ),
    ]
