# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20171010_2027'),
        ('core', '0007_auto_20171010_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiment',
            old_name='release_date',
            new_name='released_at',
        ),
        migrations.AlterField(
            model_name='omicsunittype',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='species',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterUniqueTogether(
            name='omicsunit',
            unique_together=set([('reference', 'strain', 'type')]),
        ),
        migrations.AlterUniqueTogether(
            name='strain',
            unique_together=set([('name', 'species')]),
        ),
    ]
