# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20171010_2027'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OmicsDomain',
            new_name='OmicsArea',
        ),
        migrations.AlterModelOptions(
            name='omicsarea',
            options={'verbose_name': 'Omics area', 'verbose_name_plural': 'Omics areas'},
        ),
        migrations.RenameField(
            model_name='experiment',
            old_name='omics_domain',
            new_name='omics_area',
        ),
    ]
