# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20171011_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='pixels',
        ),
        migrations.AddField(
            model_name='pixel',
            name='analysis',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='pixels', related_query_name='pixel', to='core.Analysis'),
            preserve_default=False,
        ),
    ]
