# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 13:40
from __future__ import unicode_literals

from django.db import migrations
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20171011_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, help_text='Enter a comma-separated tag string', to='core.Tag'),
        ),
    ]
