# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 09:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_experiment_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='completed_at',
            field=models.DateField(default=datetime.date(1980, 10, 14), verbose_name='Completion date'),
            preserve_default=False,
        ),
    ]
