# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-10 10:45
from __future__ import unicode_literals

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_analysis_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='notebook',
            field=models.FileField(blank=True, help_text='Upload your Jupiter Notebook or any other document helping to understand your analysis', max_length=255, upload_to=apps.core.models.Analysis.notebook_upload_to, verbose_name='Notebook'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='secondary_data',
            field=models.FileField(max_length=255, upload_to=apps.core.models.Analysis.secondary_data_upload_to, verbose_name='Secondary data'),
        ),
        migrations.AlterField(
            model_name='pixelset',
            name='pixels_file',
            field=models.FileField(max_length=255, upload_to=apps.core.models.PixelSet.pixelset_upload_to, verbose_name='Pixels file'),
        ),
    ]
