# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 13:51
from __future__ import unicode_literals

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_analysis_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='notebook_url',
        ),
        migrations.AddField(
            model_name='analysis',
            name='notebook',
            field=models.FileField(blank=True, help_text='Upload your Jupiter Notebook or any other document helping to understand your analysis', upload_to=apps.core.models.Analysis.notebook_upload_to, verbose_name='Notebook'),
        ),
    ]
