# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-22 10:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20180110_1045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysis',
            options={'ordering': ('pixeler', 'completed_at'), 'verbose_name': 'Analysis', 'verbose_name_plural': 'Analyses'},
        ),
        migrations.AlterModelOptions(
            name='experiment',
            options={'ordering': ('completed_at', 'released_at'), 'verbose_name': 'Experiment', 'verbose_name_plural': 'Experiments'},
        ),
        migrations.AlterModelOptions(
            name='omicsarea',
            options={'ordering': ('name',), 'verbose_name': 'Omics area', 'verbose_name_plural': 'Omics areas'},
        ),
        migrations.AlterModelOptions(
            name='omicsunit',
            options={'ordering': ('strain', 'reference'), 'verbose_name': 'Omics Unit', 'verbose_name_plural': 'Omics Units'},
        ),
        migrations.AlterModelOptions(
            name='omicsunittype',
            options={'ordering': ('name',), 'verbose_name': 'Omics unit type', 'verbose_name_plural': 'Omics unit types'},
        ),
        migrations.AlterModelOptions(
            name='pixel',
            options={'ordering': ('pixel_set', 'omics_unit'), 'verbose_name': 'Pixel', 'verbose_name_plural': 'Pixels'},
        ),
        migrations.AlterModelOptions(
            name='pixelset',
            options={'ordering': ('analysis', 'pixels_file'), 'verbose_name': 'Pixel set', 'verbose_name_plural': 'Pixel sets'},
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ('name',), 'verbose_name': 'Species', 'verbose_name_plural': 'Species'},
        ),
        migrations.AlterModelOptions(
            name='strain',
            options={'ordering': ('name',), 'verbose_name': 'Strain', 'verbose_name_plural': 'Strains'},
        ),
    ]
