# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionprocess',
            name='template_checksum',
            field=models.CharField(blank=True, help_text='Downloaded XLSX template checksum', max_length=64, verbose_name='Template checksum'),
        ),
        migrations.AddField(
            model_name='submissionprocess',
            name='template_version',
            field=models.CharField(blank=True, help_text='Downloaded XLSX template version', max_length=64, verbose_name='Template version'),
        ),
    ]
