# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 12:29
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_auto_20171124_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionprocess',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Submitted archive meta.xlsx parsed data', null=True, verbose_name='Meta'),
        ),
    ]
