# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0003_submissionprocess_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionprocess',
            name='validated',
            field=models.BooleanField(default=False, help_text='Check this to validate parsed metadata', verbose_name='Is validated?'),
        ),
    ]
