# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-10 10:45
from __future__ import unicode_literals

import apps.submission.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0004_auto_20171129_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionprocess',
            name='archive',
            field=models.FileField(max_length=255, upload_to=apps.submission.models.SubmissionProcess.archive_upload_to, verbose_name='Pixels submitted archive'),
        ),
    ]
