# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-11 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20180110_1045'),
        ('submission', '0005_auto_20180110_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionprocess',
            name='analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission', related_query_name='submissions', to='core.Analysis'),
        ),
    ]
