# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-15 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0007_submissionprocess_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionprocess',
            name='validated',
            field=models.BooleanField(default=False, help_text='Check this to validate parsed metadata', verbose_name='I confirm the validity of extracted meta data'),
        ),
    ]
