# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-19 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0008_auto_20180115_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionprocess',
            name='validated',
            field=models.BooleanField(default=False, help_text='Check the box above to validate the extracted metadata and enable the button.', verbose_name='I reviewed the extracted metadata on this page and I confirm their validity.'),
        ),
    ]
