# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identifier', models.CharField(blank=True, help_text='The repository identifier (e.g. PMID for PubMed)', max_length=100, verbose_name='Identifier')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('url', models.URLField(blank=True, help_text='Paste here the URL pointing to the data source', verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Entry',
                'verbose_name_plural': 'Entries',
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('url', models.URLField(blank=True, help_text='Repository root URL', verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Repository',
                'verbose_name_plural': 'Repositories',
            },
        ),
        migrations.AddField(
            model_name='entry',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', related_query_name='entry', to='data.Repository'),
        ),
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together=set([('url', 'repository'), ('identifier', 'repository')]),
        ),
    ]
