# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 10:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together=set([('url', 'repository'), ('identifier', 'repository')]),
        ),
    ]
