# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 20:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together=set([]),
        ),
    ]
