# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-22 10:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20171218_0944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ('repository', 'identifier'), 'verbose_name': 'Entry', 'verbose_name_plural': 'Entries'},
        ),
        migrations.AlterModelOptions(
            name='repository',
            options={'ordering': ('name',), 'verbose_name': 'Repository', 'verbose_name_plural': 'Repositories'},
        ),
    ]
