# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 14:06
from __future__ import unicode_literals

import apps.core.mixins
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name='ModelWithStandardID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(apps.core.mixins.UUIDModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ModelWithUUID',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            bases=(apps.core.mixins.UUIDModelMixin, models.Model),
        ),
    ]
